### ISSUE TITLE
Adicionar imagens em svg ou equivalente

### ISSUE THREAD

**Issue by iuriguilherme** [piratas/midiateca#2]
Sem a fonte da imagem não tem como consertá-la.

A imagem que enviaram no 3b5327baebc37bff8b40653d2696b69528c57d7f está com um erro que parece que fizeram de propósito, e como é que eu vou consertar se é um jpeg?

**Comment by dseeker** [comment]
se quiser editar o PDF fique a vontade. https://www.ifixit.com/Manifesto
