### ISSUE TITLE
E-mails de membros em repositório público

### ISSUE THREAD

**Issue by iuriguilherme** [piratas/midiateca#3]
Isto foi problematizado no [loomio](), os e-mails pessoais das pessoas não deveriam aparecer em repositórios públicos. Nem em histórico de commits tinha que ter isto.

Ainda se fosse tipo nome.sobrenome@membro.partidopirata.org por exemplo.

**Comment by dseeker** [comment]
voce poderia apontar para esta discussão do loomio?

**Comment by iuriguilherme** [comment]
Eu encontrei o link, mas é de um subgrupo secreto chamado "secretaria colegiada" onde só tem gente da secretaria nacional. A criação deste grupo foi deliberada e acordada, então o tópico teria que ser movido para outro grupo onde pudesse ser público, ou então a mesma discussão retomada em outro tópico de outro grupo aberto.

**Comment by RenanVilela** [comment]
Pessoal, eu não sei usar a ferramenta (GitHub), mas se alguém se dispuser a me ensinar eu ficarei feliz em poder contribuir com o projeto.

**Comment by dseeker** [comment]
@RenanVilela inicialmente se familiarize com a interface de web do github, da pra editar documentos, criar arquivos e muitas outras coisas apenas atraves do website.
existem alguns padroes de trabalho envolvendo branches, pull requests que inicialmente voce nao precisa entrar a fundo ja que é possivel reverter praticamente todas as modificações ao repositorio.

programadores tendem a usar mais a linha de comando, mas nao se afugente por isso, existem interfaces pra fazer as operacoes mais comuns

https://www.youtube.com/watch?v=neDiLHwXSVo
